[package]
name = "flooed"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = true
strip = "debuginfo"

[dependencies]
chrono = { version = "0.4.34", no-default-features = true }
dirs = "5.0.1"
notify-rust = { version = "4.10.0", no-default-features = true }
serde = { version = "1.0.196", features = [ "derive" ] }
serde_json = "1.0.113"
simple-websockets = "0.1.6"
sysinfo = "0.30.5"
webui-rs = { git = "https://github.com/SpikeHD/rust-webui", branch = "ext" }
