[package]
name = "flooed"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = true
strip = "debuginfo"

[dependencies]
dirs = "5.0.1"
serde = { version = "1.0.196", features = [ "derive" ] }
serde_json = "1.0.113"
simple-websockets = "0.1.6"
webui-rs = { git = "https://github.com/SpikeHD/rust-webui", branch = "ext" }
