name: Check backend

on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'src/**'
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'src/**'

env:
  CARGO_INCREMENTAL: 0

jobs:
  rustfmt:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt check
        run: cargo fmt -- --check

  clippy:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-20.04, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: Clippy check
        run: cargo clippy --all-targets --all-features -- -D warnings